server.port=9001
mes-configs.limitDeProduits=3
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true
management.endpoints.web.exposure.include=info, health, refresh